// <auto-generated />

#nullable enable

using ProblemDetailsApiDemo.Futurama.Shared.Models.Source.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ProblemDetailsApiDemo.Futurama.Shared.Models.Source.Entities;

public class CastMember
{
    [JsonPropertyName("id")]
    public long Id { get; set; }

    [JsonPropertyName("name")]
    public required string Name { get; set; }

    [JsonPropertyName("born")]
    public required string Born { get; set; }

    [JsonPropertyName("died")]
    public required string Died { get; set; }

    [JsonPropertyName("bio")]
    public required Bio Bio { get; set; }

    public static List<CastMember>? FromJson(string json) =>
        JsonSerializer.Deserialize<List<CastMember>>(json, Converter.Settings);
}
public class Bio
{
    [JsonPropertyName("text")]
    public required string Text { get; set; }

    [JsonPropertyName("url")]
    public required Uri Url { get; set; }
}

public static class CastMemberExtensions
{
    public static string ToJson(this List<CastMember> self) =>
        JsonSerializer.Serialize(self, Converter.Settings);
}
