// <auto-generated />

#nullable enable

using ProblemDetailsApiDemo.Futurama.Models.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ProblemDetailsApiDemo.Futurama.Models.Entities;

public class InventoryItem
{
    [JsonPropertyName("id")]
    public long Id { get; set; }

    [JsonPropertyName("title")]
    public required string Title { get; set; }

    [JsonPropertyName("category")]
    public required string Category { get; set; }

    [JsonPropertyName("description")]
    public required string Description { get; set; }

    [JsonPropertyName("slogan")]
    public required string Slogan { get; set; }

    [JsonPropertyName("price")]
    public required double Price { get; set; }

    [JsonPropertyName("stock")]
    public required long Stock { get; set; }

    public static List<InventoryItem>? FromJson(string json) =>
        JsonSerializer.Deserialize<List<InventoryItem>>(json, Converter.Settings);
}

public static class InventoryItemExtensions
{
    public static string ToJson(this List<InventoryItem> self) =>
        JsonSerializer.Serialize(self, Converter.Settings);
}
